name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
    - name: Build the Docker image in CN
      run: docker build --build-arg COUNTRY=CN -f gitea/Dockerfile -t homqyy/gitea:1.21.11-rootless-CN ./gitea
    - name: Push the Docker image in CN
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

