name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build-gitea:
    runs-on: ubuntu-latest
    env:
      DOCKER_NAME: homqyy/gitea
      DOCKER_VERSION: 1.21.11
      DOCKER_TAG: rootless
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build -f gitea/Dockerfile -t ${{ env.DOCKER_NAME }}:${{ env.DOCKER_VERSION }}-${{ env.DOCKER_TAG}} ./gitea
        docker tag ${{ env.DOCKER_NAME }}:${{ env.DOCKER_VERSION }}-${{ env.DOCKER_TAG}} ${{ env.DOCKER_NAME }}:latest
    - name: Push the Docker image
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push ${{ env.DOCKER_NAME }}:${{ env.DOCKER_VERSION }}-${{ env.DOCKER_TAG}}
        docker push ${{ env.DOCKER_NAME }}:latest
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v4
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: homqyy/gitea
        readme-filepath: ./gitea/README.md

  build-gitea-CN:
    runs-on: ubuntu-latest
    env:
      DOCKER_NAME: homqyy/gitea
      DOCKER_VERSION: 1.21.11
      DOCKER_TAG: rootless-CN
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
    - name: Build the Docker image in CN
      run: |
        docker build -f gitea/Dockerfile -t ${{ env.DOCKER_NAME }}:${{ env.DOCKER_VERSION }}-${{ env.DOCKER_TAG}} ./gitea
    - name: Push the Docker image in CN
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push ${{ env.DOCKER_NAME }}:${{ env.DOCKER_VERSION }}-${{ env.DOCKER_TAG}}

