name: ubuntu Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build-ubuntu-CN:
    runs-on: ubuntu-latest
    env:
      DOCKER_NAME: homqyy/ubuntu
      DOCKER_VERSION: 22.04
      DOCKER_TAG: CN
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
    - name: Build the Docker image in CN
      run: |
        docker build --build-arg COUNTRY=CN -f ubuntu/Dockerfile.2204 -t ${{ env.DOCKER_NAME }}:${{ env.DOCKER_VERSION }}-${{ env.DOCKER_TAG }} ./ubuntu
    - name: Push the Docker image in CN
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push ${{ env.DOCKER_NAME }}:${{ env.DOCKER_VERSION }}-${{ env.DOCKER_TAG }}
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v4
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: homqyy/ubuntu
        readme-filepath: ./ubuntu/README.md